spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=real_estate;encrypt=true;trustServerCertificate=true;
    username: sa
    password: <dM4berr-local>
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 5000
      minimum-idle: 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  mvc:
    format:
      date: dd-MM-yyyy