IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TENANTS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[TENANTS](
    [NIF] [char](11) NOT NULL,
    [ID_CARD_NUMBER] [char](8) NOT NULL,
    [FULL_NAME] [varchar](80) NOT NULL,
    [BIRTH_DATE] [date] NOT NULL,
    [ORIGINAL_ADDRESS] [varchar](100) NULL,
    [NIB] [char](25) NOT NULL
    )

ALTER TABLE [dbo].[TENANTS] ADD CONSTRAINT [PK_TENANTS] PRIMARY KEY CLUSTERED ([NIF] ASC, [ID_CARD_NUMBER] ASC, [FULL_NAME] ASC)
ALTER TABLE [dbo].[TENANTS] ADD CONSTRAINT [UK_TENANTS_NIB] UNIQUE NONCLUSTERED ([NIB] ASC)

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LANDLORDS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[LANDLORDS](
    [NIF] [char](11) NOT NULL,
    [ID_CARD_NUMBER] [char](8) NOT NULL,
    [FULL_NAME] [varchar](80) NOT NULL,
    [BIRTH_DATE] [date] NOT NULL,
    [ORIGINAL_ADDRESS] [varchar](100) NULL,
    [NIB] [char](25) NOT NULL
    )

ALTER TABLE [dbo].[LANDLORDS] ADD CONSTRAINT [PK_LANDLORDS] PRIMARY KEY CLUSTERED ([NIF] ASC, [ID_CARD_NUMBER] ASC, [FULL_NAME] ASC)
ALTER TABLE [dbo].[LANDLORDS] ADD CONSTRAINT [UK_LANDLORDS_NIB] UNIQUE NONCLUSTERED ([NIB] ASC)

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TENANT_CONTACTS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[TENANT_CONTACTS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [TENANT_NIF] [char](11) NOT NULL,
    [TENANT_ID_CARD_NUMBER] [char](8) NOT NULL,
    [TENANT_FULL_NAME] [varchar](80) NOT NULL,
    [type] [int] NOT NULL,
    [CONTACT] [nvarchar](80) NOT NULL
    )

ALTER TABLE [dbo].[TENANT_CONTACTS] ADD CONSTRAINT [PK_TENANT_CONTACTS] PRIMARY KEY CLUSTERED ([ID] ASC)
ALTER TABLE [dbo].[TENANT_CONTACTS] ADD CONSTRAINT [UK_TENANT_CONTACTS_value] UNIQUE NONCLUSTERED ([CONTACT] ASC)
ALTER TABLE [dbo].[TENANT_CONTACTS] ADD CONSTRAINT [FK_TENANT_CONTACTS_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME]
    FOREIGN KEY([TENANT_NIF], [TENANT_ID_CARD_NUMBER], [TENANT_FULL_NAME]) REFERENCES [dbo].[TENANTS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LANDLORD_CONTACTS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[LANDLORD_CONTACTS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [LANDLORD_NIF] [char](11) NOT NULL,
    [LANDLORD_ID_CARD_NUMBER] [char](8) NOT NULL,
    [LANDLORD_FULL_NAME] [varchar](80) NOT NULL,
    [type] [int] NOT NULL,
    [CONTACT] [nvarchar](80) NOT NULL
    )

ALTER TABLE [dbo].[LANDLORD_CONTACTS] ADD CONSTRAINT [PK_LANDLORD_CONTACTS] PRIMARY KEY CLUSTERED ([ID] ASC)
ALTER TABLE [dbo].[LANDLORD_CONTACTS] ADD CONSTRAINT [UK_LANDLORD_CONTACTS_value] UNIQUE NONCLUSTERED ([CONTACT] ASC)
ALTER TABLE [dbo].[LANDLORD_CONTACTS] ADD CONSTRAINT [FK_LANDLORD_CONTACTS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]
    FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME]) REFERENCES [dbo].[LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='UNITS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[UNITS](
    [ID] [varchar](80) NOT NULL,
    [LANDLORD_NIF] [char](11) NOT NULL,
    [LANDLORD_ID_CARD_NUMBER] [char](8) NOT NULL,
    [LANDLORD_FULL_NAME] [varchar](80) NOT NULL,
    [STREET] [varchar](80) NOT NULL,
    [POSTAL_CODE] [char](8) NOT NULL,
    [ARTICLE] [char](4) NOT NULL,
    [REGISTER_NUMBER] [char](4) NOT NULL,
    [TOWN] [varchar](50) NOT NULL,
    [FRACTION] [varchar](6) NOT NULL,
    [TYPOLOGY] [char](2) NOT NULL
    )

ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [PK_UNITS] PRIMARY KEY CLUSTERED ([ID] ASC)
ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [UK_UNITS_ARTICLE] UNIQUE NONCLUSTERED ([ARTICLE] ASC)
ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [UK_UNITS_POSTAL_CODE] UNIQUE NONCLUSTERED ([POSTAL_CODE] ASC)
ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [UK_UNITS_REGISTER_NUMBER] UNIQUE NONCLUSTERED ([REGISTER_NUMBER] ASC)
ALTER TABLE [dbo].[UNITS] ADD CONSTRAINT [FK_UNITS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]
    FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME]) REFERENCES [dbo].[LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='ROOMS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[ROOMS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [UNIT_ID] [varchar](80) NOT NULL,
    [AVAILABLE] [bit] NOT NULL,
    [PRICE] [int] NOT NULL,
    [CAPACITY] [tinyint] NOT NULL,
    [IS_SUITE] [bit] NOT NULL
    )

ALTER TABLE [dbo].[ROOMS] ADD CONSTRAINT [PK_ROOMS] PRIMARY KEY CLUSTERED ([ID] ASC)
ALTER TABLE [dbo].[ROOMS] ADD CONSTRAINT [FK_ROOMS_UNIT_ID] FOREIGN KEY([UNIT_ID]) REFERENCES [dbo].[UNITS] ([ID])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CONTRACTS' and xtype='U')
BEGIN
CREATE TABLE [dbo].[CONTRACTS](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [START_DATE] [date] NOT NULL,
    [END_DATE] [date] NOT NULL,
    [UNIT_ID] [varchar](80) NOT NULL,
    [ROOM_ID] [int] NULL,
    [TYPE] [varchar](10) NOT NULL
    )

ALTER TABLE [dbo].[CONTRACTS] ADD CONSTRAINT [PK_CONTRACTS] PRIMARY KEY CLUSTERED ([ID] ASC)
ALTER TABLE [dbo].[CONTRACTS] ADD CONSTRAINT [FK_CONTRACTS_ROOM_ID] FOREIGN KEY([ROOM_ID]) REFERENCES [dbo].[ROOMS] ([ID])
ALTER TABLE [dbo].[CONTRACTS] ADD CONSTRAINT [FK_CONTRACTS_UNIT_ID] FOREIGN KEY([UNIT_ID]) REFERENCES [dbo].[UNITS] ([ID])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TENANT_CONTRACT' and xtype='U')
BEGIN
CREATE TABLE [dbo].[TENANT_CONTRACT](
    [TENANT_NIF] [char](11) NOT NULL,
    [TENANT_ID_CARD_NUMBER] [char](8) NOT NULL,
    [TENANT_FULL_NAME] [varchar](80) NOT NULL,
    [CONTRACT_ID] [int] NOT NULL
    )

ALTER TABLE [dbo].[TENANT_CONTRACT] ADD CONSTRAINT [PK_TENANT_CONTRACT] PRIMARY KEY CLUSTERED ([TENANT_NIF] ASC, [TENANT_ID_CARD_NUMBER] ASC, [TENANT_FULL_NAME] ASC, [CONTRACT_ID] ASC)
ALTER TABLE [dbo].[TENANT_CONTRACT] ADD CONSTRAINT [FK_TENANT_CONTRACT_CONTRACT_ID] FOREIGN KEY([CONTRACT_ID]) REFERENCES [dbo].[CONTRACTS] ([ID])
ALTER TABLE [dbo].[TENANT_CONTRACT] ADD CONSTRAINT [FK_TENANT_CONTRACT_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME]
    FOREIGN KEY([TENANT_NIF], [TENANT_ID_CARD_NUMBER], [TENANT_FULL_NAME]) REFERENCES [dbo].[TENANTS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

END;

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='LANDLORD_CONTRACT' and xtype='U')
BEGIN
CREATE TABLE [dbo].[LANDLORD_CONTRACT](
    [LANDLORD_NIF] [char](11) NOT NULL,
    [LANDLORD_ID_CARD_NUMBER] [char](8) NOT NULL,
    [LANDLORD_FULL_NAME] [varchar](80) NOT NULL,
    [CONTRACT_ID] [int] NOT NULL
    )

ALTER TABLE [dbo].[LANDLORD_CONTRACT] ADD CONSTRAINT [PK_LANDLORD_CONTRACT] PRIMARY KEY CLUSTERED ([LANDLORD_NIF] ASC, [LANDLORD_ID_CARD_NUMBER] ASC, [LANDLORD_FULL_NAME] ASC, [CONTRACT_ID] ASC)
ALTER TABLE [dbo].[LANDLORD_CONTRACT] ADD CONSTRAINT [FK_LANDLORD_CONTRACT_CONTRACT_ID] FOREIGN KEY([CONTRACT_ID]) REFERENCES [dbo].[CONTRACTS] ([ID])
ALTER TABLE [dbo].[LANDLORD_CONTRACT] ADD CONSTRAINT [FK_LANDLORD_CONTRACT_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]
    FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME]) REFERENCES [dbo].[LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

END;