CREATE TABLE TENANTS (
    NIF char(11) NOT NULL ,
    ID_CARD_NUMBER char(8)  NOT NULL ,
    FULL_NAME varchar(80)  NOT NULL ,
    BIRTH_DATE date  NOT NULL ,
    ORIGINAL_ADDRESS varchar(100) ,
    NIB char(25)  NOT NULL ,
    PRIMARY KEY(NIF,ID_CARD_NUMBER,FULL_NAME)
);

CREATE TABLE LANDLORDS (
    NIF char(11) NOT NULL ,
    ID_CARD_NUMBER char(8)  NOT NULL ,
    FULL_NAME varchar(80)  NOT NULL ,
    BIRTH_DATE date  NOT NULL ,
    ORIGINAL_ADDRESS varchar(100) ,
    NIB char(25)  NOT NULL ,
    PRIMARY KEY(NIF,ID_CARD_NUMBER,FULL_NAME)
);

CREATE TABLE TENANT_CONTACTS (
    ID int PRIMARY KEY AUTO_INCREMENT ,
    TENANT_NIF char(11)  NOT NULL ,
    TENANT_ID_CARD_NUMBER char(8)  NOT NULL ,
    TENANT_FULL_NAME varchar(80)  NOT NULL ,
    `TYPE` int NOT NULL,
    CONTACT varchar(80)  NOT NULL ,
	FOREIGN KEY(TENANT_NIF, TENANT_ID_CARD_NUMBER, TENANT_FULL_NAME)
	REFERENCES TENANTS (NIF, ID_CARD_NUMBER, FULL_NAME)
);

CREATE TABLE LANDLORD_CONTACTS (
    ID int PRIMARY KEY AUTO_INCREMENT ,
    LANDLORD_NIF char(11)  NOT NULL ,
    LANDLORD_ID_CARD_NUMBER char(8)  NOT NULL ,
    LANDLORD_FULL_NAME varchar(80)  NOT NULL ,
    `TYPE` int NOT NULL,
    CONTACT varchar(80)  NOT NULL ,
	FOREIGN KEY(LANDLORD_NIF, LANDLORD_ID_CARD_NUMBER, LANDLORD_FULL_NAME)
	REFERENCES LANDLORDS (NIF, ID_CARD_NUMBER, FULL_NAME)
);

CREATE TABLE UNITS (
    ID varchar(80) PRIMARY KEY ,
    LANDLORD_NIF char(11)  NOT NULL ,
    LANDLORD_ID_CARD_NUMBER char(8)  NOT NULL ,
    LANDLORD_FULL_NAME varchar(80)  NOT NULL ,
    STREET varchar(80)  NOT NULL ,
    POSTAL_CODE char(8)  NOT NULL ,
    ARTICLE char(4)  NOT NULL ,
    REGISTER_NUMBER char(4)  NOT NULL ,
    TOWN varchar(50)  NOT NULL ,
    FRACTION varchar(6)  NOT NULL ,
    TYPOLOGY char(2)  NOT NULL ,
    FOREIGN KEY(LANDLORD_NIF, LANDLORD_ID_CARD_NUMBER, LANDLORD_FULL_NAME)
	REFERENCES LANDLORDS (NIF, ID_CARD_NUMBER, FULL_NAME)
);

CREATE TABLE ROOMS (
    ID int PRIMARY KEY AUTO_INCREMENT ,
    UNIT_ID varchar(80)  NOT NULL ,
    AVAILABLE bit  NOT NULL ,
    PRICE int  NOT NULL,
    CAPACITY tinyint  NOT NULL ,
    IS_SUITE bit  NOT NULL ,
	FOREIGN KEY(UNIT_ID)
	REFERENCES UNITS (ID)
);

CREATE TABLE CONTRACTS (
    ID int PRIMARY KEY AUTO_INCREMENT ,
    START_DATE date  NOT NULL ,
    END_DATE date  NOT NULL ,
    UNIT_ID varchar(80)  NOT NULL ,
    ROOM_ID int  NULL ,
    `TYPE` varchar(80) NOT NULL ,
	FOREIGN KEY(UNIT_ID)
	REFERENCES UNITS (ID),
	FOREIGN KEY(ROOM_ID)
	REFERENCES ROOMS (ID)
);

CREATE TABLE TENANT_CONTRACT (
    TENANT_NIF char(11)  NOT NULL ,
    TENANT_ID_CARD_NUMBER char(8)  NOT NULL ,
    TENANT_FULL_NAME varchar(80)  NOT NULL ,
    CONTRACT_ID int  NOT NULL ,
    PRIMARY KEY(TENANT_NIF,TENANT_ID_CARD_NUMBER,TENANT_FULL_NAME,CONTRACT_ID) ,
	FOREIGN KEY(TENANT_NIF,TENANT_ID_CARD_NUMBER,TENANT_FULL_NAME)
	REFERENCES TENANTS (NIF,ID_CARD_NUMBER,FULL_NAME) ,
    FOREIGN KEY(CONTRACT_ID)
	REFERENCES CONTRACTS (ID)
);

CREATE TABLE LANDLORD_CONTRACT (
    LANDLORD_NIF char(11)  NOT NULL ,
    LANDLORD_ID_CARD_NUMBER char(8)  NOT NULL ,
    LANDLORD_FULL_NAME varchar(80)  NOT NULL ,
    CONTRACT_ID int  NOT NULL ,
    PRIMARY KEY(LANDLORD_NIF,LANDLORD_ID_CARD_NUMBER,LANDLORD_FULL_NAME,CONTRACT_ID) ,
	FOREIGN KEY(LANDLORD_NIF,LANDLORD_ID_CARD_NUMBER,LANDLORD_FULL_NAME)
	REFERENCES LANDLORDS (NIF,ID_CARD_NUMBER,FULL_NAME) ,
    FOREIGN KEY(CONTRACT_ID)
	REFERENCES CONTRACTS (ID)
);
