CREATE TABLE [LANDLORDS]  (
    [NIF] char(11)  NOT NULL ,
    [ID_CARD_NUMBER] char(8)  NOT NULL ,
    [FULL_NAME] varchar(80)  NOT NULL ,
    [BIRTH_DATE] date  NOT NULL ,
    [ORIGINAL_ADDRESS] varchar(100)  NULL ,
    [NIB] char(25)  NOT NULL ,
    CONSTRAINT [PK_LANDLORDS] PRIMARY KEY CLUSTERED (
        [NIF] ASC,[ID_CARD_NUMBER] ASC,[FULL_NAME] ASC
    ),
    CONSTRAINT [UK_LANDLORDS_NIB] UNIQUE (
        [NIB]
    )
)

CREATE TABLE [LANDLORD_CONTACTS] (
    [ID] int IDENTITY(1,1) NOT NULL ,
    [LANDLORD_NIF] char(11)  NOT NULL ,
    [LANDLORD_ID_CARD_NUMBER] char(8)  NOT NULL ,
    [LANDLORD_FULL_NAME] varchar(80)  NOT NULL ,
    [TYPE] int  NOT NULL ,
    [CONTACT] nvarchar(80)  NOT NULL ,
    CONSTRAINT [PK_LANDLORD_CONTACTS] PRIMARY KEY CLUSTERED (
        [ID] ASC
    ),
    CONSTRAINT [UK_LANDLORD_CONTACTS_CONTACT] UNIQUE (
        [CONTACT]
    )
)

CREATE TABLE [TENANTS] (
    [NIF] char(11)  NOT NULL ,
    [ID_CARD_NUMBER] char(8)  NOT NULL ,
    [FULL_NAME] varchar(80)  NOT NULL ,
    [BIRTH_DATE] date  NOT NULL ,
    [ORIGINAL_ADDRESS] varchar(100)  NULL ,
    [NIB] char(25)  NOT NULL ,
    CONSTRAINT [PK_TENANTS] PRIMARY KEY CLUSTERED (
        [NIF] ASC,[ID_CARD_NUMBER] ASC,[FULL_NAME] ASC
    ),
    CONSTRAINT [UK_TENANTS_NIB] UNIQUE (
        [NIB]
    )
)

CREATE TABLE [TENANT_CONTACTS] (
    [ID] int IDENTITY(1,1) NOT NULL ,
    [TENANT_NIF] char(11)  NOT NULL ,
    [TENANT_ID_CARD_NUMBER] char(8)  NOT NULL ,
    [TENANT_FULL_NAME] varchar(80)  NOT NULL ,
    [TYPE] int  NOT NULL ,
    [CONTACT] nvarchar(80)  NOT NULL ,
    CONSTRAINT [PK_TENANT_CONTACTS] PRIMARY KEY CLUSTERED (
        [ID] ASC
    ),
    CONSTRAINT [UK_TENANT_CONTACTS_CONTACT] UNIQUE (
        [CONTACT]
    )
)

CREATE TABLE [UNITS] (
    [ID] varchar(80)  NOT NULL ,
    [LANDLORD_NIF] char(11)  NOT NULL ,
    [LANDLORD_ID_CARD_NUMBER] char(8)  NOT NULL ,
    [LANDLORD_FULL_NAME] varchar(80)  NOT NULL ,
    [STREET] varchar(80)  NOT NULL ,
    [POSTAL_CODE] char(8)  NOT NULL ,
    [ARTICLE] char(4)  NOT NULL ,
    [REGISTER_NUMBER] char(4)  NOT NULL ,
    [TOWN] varchar(50)  NOT NULL ,
    [FRACTION] varchar(6)  NOT NULL ,
    [TYPOLOGY] char(2)  NOT NULL ,
    CONSTRAINT [PK_UNITS] PRIMARY KEY CLUSTERED (
        [ID] ASC
    ),
    CONSTRAINT [UK_UNITS_POSTAL_CODE] UNIQUE (
        [POSTAL_CODE]
    ),
    CONSTRAINT [UK_UNITS_ARTICLE] UNIQUE (
        [ARTICLE]
    ),
    CONSTRAINT [UK_UNITS_REGISTER_NUMBER] UNIQUE (
        [REGISTER_NUMBER]
    )
)

CREATE TABLE [ROOMS] (
    [ID] int IDENTITY(1,1) NOT NULL ,
    [UNIT_ID] varchar(80)  NOT NULL ,
    [AVAILABLE] bit  NOT NULL ,
    [PRICE] int  NOT NULL ,
    [CAPACITY] tinyint  NOT NULL ,
    [IS_SUITE] bit  NOT NULL ,
    CONSTRAINT [PK_ROOMS] PRIMARY KEY CLUSTERED (
        [ID] ASC
    )
)

CREATE TABLE [CONTRACTS] (
    [ID] int IDENTITY(1,1) NOT NULL ,
    [START_DATE] date  NOT NULL ,
    [END_DATE] date  NOT NULL ,
    [UNIT_ID] varchar(80)  NOT NULL ,
    [ROOM_ID] int  NULL ,
    [TYPE] varchar(10)  NOT NULL ,
    CONSTRAINT [PK_CONTRACTS] PRIMARY KEY CLUSTERED (
        [ID] ASC
    )
)

CREATE TABLE [TENANT_CONTRACT] (
    [TENANT_NIF] char(11)  NOT NULL ,
    [TENANT_ID_CARD_NUMBER] char(8)  NOT NULL ,
    [TENANT_FULL_NAME] varchar(80)  NOT NULL ,
    [CONTRACT_ID] int  NOT NULL ,
    CONSTRAINT [PK_TENANT_CONTRACT] PRIMARY KEY CLUSTERED (
        [TENANT_NIF] ASC,[TENANT_ID_CARD_NUMBER] ASC,[TENANT_FULL_NAME] ASC,[CONTRACT_ID] ASC
    )
)

CREATE TABLE [LANDLORD_CONTRACT] (
    [LANDLORD_NIF] char(11)  NOT NULL ,
    [LANDLORD_ID_CARD_NUMBER] char(8)  NOT NULL ,
    [LANDLORD_FULL_NAME] varchar(80)  NOT NULL ,
    [CONTRACT_ID] int  NOT NULL ,
    CONSTRAINT [PK_LANDLORD_CONTRACT] PRIMARY KEY CLUSTERED (
        [LANDLORD_NIF] ASC,[LANDLORD_ID_CARD_NUMBER] ASC,[LANDLORD_FULL_NAME] ASC,[CONTRACT_ID] ASC
    )
)

ALTER TABLE [LANDLORD_CONTACTS] WITH CHECK ADD CONSTRAINT [FK_LANDLORD_CONTACTS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME] FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME])
REFERENCES [LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

ALTER TABLE [LANDLORD_CONTACTS] CHECK CONSTRAINT [FK_LANDLORD_CONTACTS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]

ALTER TABLE [LANDLORD_CONTRACT] WITH CHECK ADD CONSTRAINT [FK_LANDLORD_CONTRACT_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME] FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME])
REFERENCES [LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

ALTER TABLE [LANDLORD_CONTRACT] CHECK CONSTRAINT [FK_LANDLORD_CONTRACT_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]

ALTER TABLE [LANDLORD_CONTRACT] WITH CHECK ADD CONSTRAINT [FK_LANDLORD_CONTRACT_CONTRACT_ID] FOREIGN KEY([CONTRACT_ID])
REFERENCES [CONTRACTS] ([ID])

ALTER TABLE [LANDLORD_CONTRACT] CHECK CONSTRAINT [FK_LANDLORD_CONTRACT_CONTRACT_ID]

ALTER TABLE [TENANT_CONTACTS] WITH CHECK ADD CONSTRAINT [FK_TENANT_CONTACTS_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME] FOREIGN KEY([TENANT_NIF], [TENANT_ID_CARD_NUMBER], [TENANT_FULL_NAME])
REFERENCES [TENANTS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

ALTER TABLE [TENANT_CONTACTS] CHECK CONSTRAINT [FK_TENANT_CONTACTS_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME]

ALTER TABLE [TENANT_CONTRACT] WITH CHECK ADD CONSTRAINT [FK_TENANT_CONTRACT_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME] FOREIGN KEY([TENANT_NIF], [TENANT_ID_CARD_NUMBER], [TENANT_FULL_NAME])
REFERENCES [TENANTS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

ALTER TABLE [TENANT_CONTRACT] CHECK CONSTRAINT [FK_TENANT_CONTRACT_TENANT_NIF_TENANT_ID_CARD_NUMBER_TENANT_FULL_NAME]

ALTER TABLE [TENANT_CONTRACT] WITH CHECK ADD CONSTRAINT [FK_TENANT_CONTRACT_CONTRACT_ID] FOREIGN KEY([CONTRACT_ID])
REFERENCES [CONTRACTS] ([ID])

ALTER TABLE [TENANT_CONTRACT] CHECK CONSTRAINT [FK_TENANT_CONTRACT_CONTRACT_ID]

ALTER TABLE [UNITS] WITH CHECK ADD CONSTRAINT [FK_UNITS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME] FOREIGN KEY([LANDLORD_NIF], [LANDLORD_ID_CARD_NUMBER], [LANDLORD_FULL_NAME])
REFERENCES [LANDLORDS] ([NIF], [ID_CARD_NUMBER], [FULL_NAME])

ALTER TABLE [UNITS] CHECK CONSTRAINT [FK_UNITS_LANDLORD_NIF_LANDLORD_ID_CARD_NUMBER_LANDLORD_FULL_NAME]

ALTER TABLE [ROOMS] WITH CHECK ADD CONSTRAINT [FK_ROOMS_UNIT_ID] FOREIGN KEY([UNIT_ID])
REFERENCES [UNITS] ([ID])

ALTER TABLE [ROOMS] CHECK CONSTRAINT [FK_ROOMS_UNIT_ID]

ALTER TABLE [CONTRACTS] WITH CHECK ADD CONSTRAINT [FK_CONTRACTS_UNIT_ID] FOREIGN KEY([UNIT_ID])
REFERENCES [UNITS] ([ID])

ALTER TABLE [CONTRACTS] CHECK CONSTRAINT [FK_CONTRACTS_UNIT_ID]

ALTER TABLE [CONTRACTS] WITH CHECK ADD CONSTRAINT [FK_CONTRACTS_ROOM_ID] FOREIGN KEY([ROOM_ID])
REFERENCES [ROOMS] ([ID])

ALTER TABLE [CONTRACTS] CHECK CONSTRAINT [FK_CONTRACTS_ROOM_ID]
